[build]
builder = "DOCKERFILE"
dockerfilePath = "server/Dockerfile"
buildContext = "server"

[deploy]
startCommand = "npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

